// PALAPA - TypeScript Type Definitions
// Based on Firestore Collections Schema

import { Timestamp } from 'firebase/firestore';

// Base types
export type PriceRange = 'murah' | 'sedang' | 'mahal';
export type Category = 'alam' | 'budaya' | 'kuliner' | 'religius' | 'petualangan' | 'belanja';
export type Province = 'aceh' | 'sumatera-utara' | 'sumatera-barat' | 'riau' | 'jambi' | 'sumatera-selatan' |
                      'bengkulu' | 'lampung' | 'kepulauan-bangka-belitung' | 'kepulauan-riau' | 'dki-jakarta' |
                      'jawa-barat' | 'jawa-tengah' | 'di-yogyakarta' | 'jawa-timur' | 'banten' | 'bali' |
                      'nusa-tenggara-barat' | 'nusa-tenggara-timur' | 'kalimantan-barat' | 'kalimantan-tengah' |
                      'kalimantan-selatan' | 'kalimantan-timur' | 'kalimantan-utara' | 'sulawesi-utara' |
                      'sulawesi-tengah' | 'sulawesi-selatan' | 'sulawesi-tenggara' | 'gorontalo' | 'sulawesi-barat' |
                      'maluku' | 'maluku-utara' | 'papua-barat' | 'papua';

// Firestore Document Base
export interface FirestoreDoc {
  id?: string; // Auto-generated by Firestore
  createdAt: Timestamp;
  updatedAt: Timestamp;
}

// Destinations Collection
export interface Destination extends FirestoreDoc {
  name: string;
  category: Category;
  latitude: number;
  longitude: number;
  address: string;
  description: string;
  descriptionClean: string;
  priceRange: PriceRange;
  rating: number;
  timeMinutes: number; // Estimated visit time in minutes
  imageUrl: string;
  imagePath: string;
  provinsi: Province;
  kotaKabupaten: string;
  isCultural: boolean;
  umkmId?: string | null; // Reference to UMKM if available
}

// UMKM Collection
export interface UMKM extends FirestoreDoc {
  name: string;
  category: 'batik' | 'kuliner' | 'kerajinan';
  latitude: number;
  longitude: number;
  address: string;
  phone: string;
  whatsapp: string;
  verified: boolean;
}

// Users Collection (extends Firebase Auth)
export interface UserProfile extends FirestoreDoc {
  uid: string; // From Firebase Auth
  budgetRange?: PriceRange | null;
  preferredCategories?: Category[];
}

// Itineraries Collection
export interface Itinerary extends FirestoreDoc {
  userId: string;
  destinations: string[]; // Array of destination IDs
  totalBudget: number;
  durationDays: number;
  geminiResponse: any; // Structured JSON from Gemini API
}

// API Request/Response Types

// Destinations API
export interface GetDestinationsRequest {
  provinsi?: Province;
  kategori?: Category;
  is_cultural?: boolean;
  limit?: number;
  offset?: number;
}

export interface GetDestinationsResponse {
  destinations: Destination[];
  total: number;
  hasMore: boolean;
}

// Itinerary API
export interface CreateItineraryRequest {
  budget: number;
  duration_days: number;
  preferred_categories: Category[];
  provinsi?: Province;
}

export interface CreateItineraryResponse {
  itinerary: {
    days: DayItinerary[];
    totalBudget: number;
    tips: string[];
  };
  total_budget: number;
  gemini_response: any;
}

export interface DayItinerary {
  day: number;
  destinations: Destination[];
  activities: string[];
  meals?: string[];
  transportation?: string;
}

// Vector Search API
export interface VectorSearchRequest {
  query: string;
  limit?: number;
  filters?: {
    provinsi?: Province;
    kategori?: Category;
    isCultural?: boolean;
  };
}

export interface VectorSearchResponse {
  destinations: Destination[];
  scores: number[];
}

// Weather API
export interface WeatherRequest {
  lat: number;
  lng: number;
  days?: number;
}

export interface WeatherResponse {
  forecast: WeatherDay[];
  current: WeatherCurrent;
}

export interface WeatherDay {
  date: string;
  temp_min: number;
  temp_max: number;
  humidity: number;
  description: string;
  icon: string;
  rain_chance?: number;
}

export interface WeatherCurrent {
  temp: number;
  humidity: number;
  description: string;
  icon: string;
  wind_speed: number;
}

// Route Optimization API
export interface RouteOptimizationRequest {
  destinations: { lat: number; lng: number; id: string }[];
  startPoint?: { lat: number; lng: number };
}

export interface RouteOptimizationResponse {
  optimizedRoute: OptimizedDestination[];
  totalDistance: number;
  estimatedTime: number;
}

export interface OptimizedDestination {
  id: string;
  name: string;
  lat: number;
  lng: number;
  order: number;
  distanceToNext?: number;
  timeToNext?: number;
}

// Research API
export interface ResearchRequest {
  query: string;
  type: 'destination' | 'cultural' | 'general';
}

export interface ResearchResponse {
  answer: string;
  citations: Citation[];
  sources: string[];
}

export interface Citation {
  text: string;
  source: string;
  url?: string;
}

// Parlant Session Types
export interface ParlantSessionRequest {
  agent_id: string;
  customer_id: string;
  title: string;
}

export interface ParlantSessionResponse {
  session_id: string;
  agent_id: string;
  customer_id: string;
  creation_utc: string;
}

export interface ParlantEventRequest {
  session_id: string;
  kind: 'message';
  source: 'customer';
  message: string;
}

export interface ParlantEventResponse {
  events: ParlantEvent[];
}

export interface ParlantEvent {
  id: string;
  kind: 'message' | 'status';
  source: 'customer' | 'agent';
  message?: string;
  status?: 'processing' | 'typing' | 'ready';
  timestamp: string;
}

// Gemini API Types
export interface GeminiItineraryRequest {
  budget: number;
  duration_days: number;
  preferred_categories: Category[];
  provinsi?: Province;
  existing_destinations?: Destination[];
}

export interface GeminiItineraryResponse {
  days: DayItinerary[];
  totalBudget: number;
  tips: string[];
  cultural_notes: string[];
}

// FAISS Types
export interface FAISSSearchResult {
  id: string;
  score?: number; // Optional for stored results, required for search results
  name: string;
  category: Category;
  provinsi: Province;
  isCultural: boolean;
  [key: string]: any; // Allow additional properties
}

// Error Types
export interface APIError {
  error: string;
  code?: string;
  details?: any;
}

// Utility Types
export type WithId<T> = T & { id: string };
export type WithoutId<T> = Omit<T, 'id'>;

// Search and Filter Types
export interface SearchFilters {
  provinsi?: Province[];
  kategori?: Category[];
  isCultural?: boolean;
  priceRange?: PriceRange[];
  rating?: {
    min: number;
    max: number;
  };
}

export interface SortOptions {
  field: 'name' | 'rating' | 'priceRange' | 'createdAt';
  direction: 'asc' | 'desc';
}

// Pagination Types
export interface PaginationOptions {
  limit: number;
  offset?: number;
  cursor?: string;
}

export interface PaginatedResponse<T> {
  data: T[];
  total: number;
  hasMore: boolean;
  nextCursor?: string;
}
