#!/usr/bin/env python3
"""
Create Manual UMKM Data for Yogyakarta
Create 30 authentic UMKM entries for Yogyakarta with proper data structure
"""

import json
from typing import List, Dict, Any

def create_umkm_data() -> List[Dict[str, Any]]:
    """Create 30 UMKM entries for Yogyakarta"""

    umkm_data = [
        # 1-5: Batik
        {
            "name": "Batik Keris Jogja",
            "category": "batik",
            "description": "Batik tulis handmade dengan motif klasik Yogyakarta. Spesialis batik untuk kebaya dan kain tradisional.",
            "address": "Jl. Malioboro No. 45, Yogyakarta",
            "provinsi": "DI Yogyakarta",
            "kotaKabupaten": "Yogyakarta",
            "latitude": -7.7956,
            "longitude": 110.3695,
            "priceRange": "mahal",
            "rating": 4.8,
            "timeMinutes": 60,
            "contact": "+62 274 123456",
            "imageUrl": "",
            "imagePath": "",
            "isCultural": True,
            "umkmId": None
        },
        {
            "name": "Batik Parangkusumo",
            "category": "batik",
            "description": "Batik cap dan tulis dengan motif parang yang terkenal. Cocok untuk souvenir dan fashion modern.",
            "address": "Jl. Prawirotaman No. 8, Yogyakarta",
            "provinsi": "DI Yogyakarta",
            "kotaKabupaten": "Yogyakarta",
            "latitude": -7.8167,
            "longitude": 110.3667,
            "priceRange": "sedang",
            "rating": 4.6,
            "timeMinutes": 45,
            "contact": "+62 274 234567",
            "imageUrl": "",
            "imagePath": "",
            "isCultural": True,
            "umkmId": None
        },
        {
            "name": "Galeri Batik Yogyakarta",
            "category": "batik",
            "description": "Galeri batik modern dengan desain kontemporer. Menggabungkan motif tradisional dengan tren fashion terkini.",
            "address": "Jl. Tirtodipuran No. 12, Yogyakarta",
            "provinsi": "DI Yogyakarta",
            "kotaKabupaten": "Yogyakarta",
            "latitude": -7.7833,
            "longitude": 110.3667,
            "priceRange": "mahal",
            "rating": 4.7,
            "timeMinutes": 90,
            "contact": "+62 274 345678",
            "imageUrl": "",
            "imagePath": "",
            "isCultural": True,
            "umkmId": None
        },
        {
            "name": "Batik Semarangan",
            "category": "batik",
            "description": "Batik tulis dengan motif semarangan yang indah. Spesialis untuk acara adat dan pernikahan.",
            "address": "Jl. Sagan No. 25, Yogyakarta",
            "provinsi": "DI Yogyakarta",
            "kotaKabupaten": "Yogyakarta",
            "latitude": -7.7667,
            "longitude": 110.3667,
            "priceRange": "mahal",
            "rating": 4.5,
            "timeMinutes": 75,
            "contact": "+62 274 456789",
            "imageUrl": "",
            "imagePath": "",
            "isCultural": True,
            "umkmId": None
        },
        {
            "name": "Batik Cap Jogja Asli",
            "category": "batik",
            "description": "Batik cap dengan harga terjangkau namun kualitas tinggi. Cocok untuk souvenir dan pakaian sehari-hari.",
            "address": "Jl. Malioboro No. 78, Yogyakarta",
            "provinsi": "DI Yogyakarta",
            "kotaKabupaten": "Yogyakarta",
            "latitude": -7.7928,
            "longitude": 110.3658,
            "priceRange": "murah",
            "rating": 4.3,
            "timeMinutes": 30,
            "contact": "+62 274 567890",
            "imageUrl": "",
            "imagePath": "",
            "isCultural": True,
            "umkmId": None
        },

        # 6-10: Perak Kotagede
        {
            "name": "Perak Kotagede Indah",
            "category": "perak",
            "description": "Perhiasan perak handmade dengan desain klasik Yogyakarta. Cincin, gelang, dan kalung dengan filigran detail.",
            "address": "Jl. Mondorakan No. 15, Kotagede, Yogyakarta",
            "provinsi": "DI Yogyakarta",
            "kotaKabupaten": "Yogyakarta",
            "latitude": -7.8167,
            "longitude": 110.4,
            "priceRange": "mahal",
            "rating": 4.8,
            "timeMinutes": 120,
            "contact": "+62 274 678901",
            "imageUrl": "",
            "imagePath": "",
            "isCultural": True,
            "umkmId": None
        },
        {
            "name": "Kerajinan Perak Hamzah",
            "category": "perak",
            "description": "Perak Kotagede dengan teknik tempa dan ukir tradisional. Spesialis untuk perhiasan adat Jawa.",
            "address": "Jl. Mondorakan No. 28, Kotagede, Yogyakarta",
            "provinsi": "DI Yogyakarta",
            "kotaKabupaten": "Yogyakarta",
            "latitude": -7.8208,
            "longitude": 110.4025,
            "priceRange": "mahal",
            "rating": 4.7,
            "timeMinutes": 90,
            "contact": "+62 274 789012",
            "imageUrl": "",
            "imagePath": "",
            "isCultural": True,
            "umkmId": None
        },
        {
            "name": "Silver Craft Kotagede",
            "category": "perak",
            "description": "Perhiasan perak modern dengan sentuhan kontemporer. Menggabungkan desain klasik dengan tren fashion.",
            "address": "Jl. Kemasan No. 12, Kotagede, Yogyakarta",
            "provinsi": "DI Yogyakarta",
            "kotaKabupaten": "Yogyakarta",
            "latitude": -7.8133,
            "longitude": 110.3983,
            "priceRange": "sedang",
            "rating": 4.5,
            "timeMinutes": 60,
            "contact": "+62 274 890123",
            "imageUrl": "",
            "imagePath": "",
            "isCultural": True,
            "umkmId": None
        },
        {
            "name": "Perak Filigree Yogyakarta",
            "category": "perak",
            "description": "Spesialis filigree perak dengan detail yang sangat halus. Cocok untuk hadiah spesial dan koleksi.",
            "address": "Jl. Mondorakan No. 45, Kotagede, Yogyakarta",
            "provinsi": "DI Yogyakarta",
            "kotaKabupaten": "Yogyakarta",
            "latitude": -7.8189,
            "longitude": 110.4011,
            "priceRange": "mahal",
            "rating": 4.9,
            "timeMinutes": 150,
            "contact": "+62 274 901234",
            "imageUrl": "",
            "imagePath": "",
            "isCultural": True,
            "umkmId": None
        },
        {
            "name": "Perhiasan Perak Murah",
            "category": "perak",
            "description": "Perhiasan perak dengan harga terjangkau namun tetap berkualitas. Cocok untuk souvenir dan aksesoris sehari-hari.",
            "address": "Jl. Kemasan No. 25, Kotagede, Yogyakarta",
            "provinsi": "DI Yogyakarta",
            "kotaKabupaten": "Yogyakarta",
            "latitude": -7.8156,
            "longitude": 110.3994,
            "priceRange": "murah",
            "rating": 4.2,
            "timeMinutes": 45,
            "contact": "+62 274 012345",
            "imageUrl": "",
            "imagePath": "",
            "isCultural": True,
            "umkmId": None
        },

        # 11-15: Kuliner Tradisional
        {
            "name": "Gudeg Yu Djum",
            "category": "kuliner",
            "description": "Gudeg Jogja yang legendaris dengan cita rasa autentik. Disajikan dengan ayam, telur, dan sambal krecek.",
            "address": "Jl. Wijilan No. 1, Yogyakarta",
            "provinsi": "DI Yogyakarta",
            "kotaKabupaten": "Yogyakarta",
            "latitude": -7.8,
            "longitude": 110.3667,
            "priceRange": "murah",
            "rating": 4.6,
            "timeMinutes": 30,
            "contact": "+62 274 123456",
            "imageUrl": "",
            "imagePath": "",
            "isCultural": True,
            "umkmId": None
        },
        {
            "name": "Bakpia Kukus Jogja",
            "category": "kuliner",
            "description": "Bakpia kukus khas Pathuk dengan berbagai varian rasa. Camilan manis yang wajib dicoba di Jogja.",
            "address": "Jl. Mataram No. 15, Yogyakarta",
            "provinsi": "DI Yogyakarta",
            "kotaKabupaten": "Yogyakarta",
            "latitude": -7.7833,
            "longitude": 110.3833,
            "priceRange": "murah",
            "rating": 4.4,
            "timeMinutes": 15,
            "contact": "+62 274 234567",
            "imageUrl": "",
            "imagePath": "",
            "isCultural": True,
            "umkmId": None
        },
        {
            "name": "Sate Klathak Pak Pong",
            "category": "kuliner",
            "description": "Sate klatak dengan bumbu tradisional Yogyakarta. Daging sapi yang empuk dengan kuah yang gurih.",
            "address": "Jl. Imogiri Timur No. 8, Yogyakarta",
            "provinsi": "DI Yogyakarta",
            "kotaKabupaten": "Yogyakarta",
            "latitude": -7.8167,
            "longitude": 110.4,
            "priceRange": "sedang",
            "rating": 4.7,
            "timeMinutes": 45,
            "contact": "+62 274 345678",
            "imageUrl": "",
            "imagePath": "",
            "isCultural": True,
            "umkmId": None
        },
        {
            "name": "Wedang Ronde Mbah Marto",
            "category": "kuliner",
            "description": "Wedang ronde hangat dengan bola-bola ketan. Minuman tradisional yang cocok untuk malam hari.",
            "address": "Jl. Malioboro No. 35, Yogyakarta",
            "provinsi": "DI Yogyakarta",
            "kotaKabupaten": "Yogyakarta",
            "latitude": -7.7939,
            "longitude": 110.3661,
            "priceRange": "murah",
            "rating": 4.3,
            "timeMinutes": 20,
            "contact": "+62 274 456789",
            "imageUrl": "",
            "imagePath": "",
            "isCultural": True,
            "umkmId": None
        },
        {
            "name": "Kopi Joss Manggar",
            "category": "kuliner",
            "description": "Kopi joss dengan arang panas di dalamnya. Pengalaman unik menikmati kopi tradisional Yogyakarta.",
            "address": "Jl. Prawirotaman No. 22, Yogyakarta",
            "provinsi": "DI Yogyakarta",
            "kotaKabupaten": "Yogyakarta",
            "latitude": -7.8167,
            "longitude": 110.3667,
            "priceRange": "murah",
            "rating": 4.5,
            "timeMinutes": 25,
            "contact": "+62 274 567890",
            "imageUrl": "",
            "imagePath": "",
            "isCultural": True,
            "umkmId": None
        },

        # 16-20: Kerajinan Lainnya
        {
            "name": "Wayang Kulit Pak Dalang",
            "category": "wayang",
            "description": "Wayang kulit handmade dengan ukiran detail. Termasuk pertunjukan wayang dan workshop pembuatan wayang.",
            "address": "Jl. Prawirotaman No. 30, Yogyakarta",
            "provinsi": "DI Yogyakarta",
            "kotaKabupaten": "Yogyakarta",
            "latitude": -7.8156,
            "longitude": 110.3678,
            "priceRange": "mahal",
            "rating": 4.8,
            "timeMinutes": 180,
            "contact": "+62 274 678901",
            "imageUrl": "",
            "imagePath": "",
            "isCultural": True,
            "umkmId": None
        },
        {
            "name": "Tenun Ikat Jogja",
            "category": "tenun",
            "description": "Kain tenun ikat dengan motif tradisional Yogyakarta. Menggunakan pewarna alami dan teknik handwoven.",
            "address": "Jl. Tirtodipuran No. 18, Yogyakarta",
            "provinsi": "DI Yogyakarta",
            "kotaKabupaten": "Yogyakarta",
            "latitude": -7.7839,
            "longitude": 110.3672,
            "priceRange": "mahal",
            "rating": 4.6,
            "timeMinutes": 120,
            "contact": "+62 274 789012",
            "imageUrl": "",
            "imagePath": "",
            "isCultural": True,
            "umkmId": None
        },
        {
            "name": "Kerajinan Kayu Jati",
            "category": "kayu",
            "description": "Furniture dan dekorasi dari kayu jati asli Yogyakarta. Meja, kursi, dan ukiran dengan desain klasik.",
            "address": "Jl. Kaliurang KM 8, Yogyakarta",
            "provinsi": "DI Yogyakarta",
            "kotaKabupaten": "Yogyakarta",
            "latitude": -7.7167,
            "longitude": 110.4167,
            "priceRange": "mahal",
            "rating": 4.7,
            "timeMinutes": 200,
            "contact": "+62 274 890123",
            "imageUrl": "",
            "imagePath": "",
            "isCultural": True,
            "umkmId": None
        },
        {
            "name": "Blangkon Tradisional",
            "category": "tekstil",
            "description": "Blangkon dan udeng dengan berbagai motif batik. Aksesoris kepala tradisional Jawa yang berkualitas.",
            "address": "Jl. Malioboro No. 55, Yogyakarta",
            "provinsi": "DI Yogyakarta",
            "kotaKabupaten": "Yogyakarta",
            "latitude": -7.7944,
            "longitude": 110.3661,
            "priceRange": "sedang",
            "rating": 4.4,
            "timeMinutes": 40,
            "contact": "+62 274 901234",
            "imageUrl": "",
            "imagePath": "",
            "isCultural": True,
            "umkmId": None
        },
        {
            "name": "Kerajinan Bambu Jogja",
            "category": "bambu",
            "description": "Kerajinan bambu untuk dekorasi rumah dan taman. Tas, lampu, dan furniture dari bambu alami.",
            "address": "Jl. Magelang KM 5, Yogyakarta",
            "provinsi": "DI Yogyakarta",
            "kotaKabupaten": "Yogyakarta",
            "latitude": -7.75,
            "longitude": 110.3833,
            "priceRange": "sedang",
            "rating": 4.3,
            "timeMinutes": 80,
            "contact": "+62 274 012345",
            "imageUrl": "",
            "imagePath": "",
            "isCultural": True,
            "umkmId": None
        },

        # 21-25: UMKM Modern dengan Sentuhan Budaya
        {
            "name": "Toko Oleh-oleh Jogja",
            "category": "oleh-oleh",
            "description": "Koleksi lengkap oleh-oleh khas Yogyakarta. Gudeg, bakpia, batik, dan kerajinan tangan dalam satu tempat.",
            "address": "Jl. Malioboro No. 20, Yogyakarta",
            "provinsi": "DI Yogyakarta",
            "kotaKabupaten": "Yogyakarta",
            "latitude": -7.7925,
            "longitude": 110.3656,
            "priceRange": "sedang",
            "rating": 4.5,
            "timeMinutes": 50,
            "contact": "+62 274 123456",
            "imageUrl": "",
            "imagePath": "",
            "isCultural": True,
            "umkmId": None
        },
        {
            "name": "Fashion Muslim Jogja",
            "category": "fashion",
            "description": "Pakaian muslim dengan motif batik dan tenun. Gamis, hijab, dan aksesoris dengan sentuhan budaya Yogyakarta.",
            "address": "Jl. Prawirotaman No. 35, Yogyakarta",
            "provinsi": "DI Yogyakarta",
            "kotaKabupaten": "Yogyakarta",
            "latitude": -7.8147,
            "longitude": 110.3681,
            "priceRange": "sedang",
            "rating": 4.6,
            "timeMinutes": 70,
            "contact": "+62 274 234567",
            "imageUrl": "",
            "imagePath": "",
            "isCultural": True,
            "umkmId": None
        },
        {
            "name": "Workshop Batik Anak",
            "category": "edukasi",
            "description": "Workshop membatik untuk anak-anak dan keluarga. Belajar seni batik dengan cara yang menyenangkan.",
            "address": "Jl. Tirtodipuran No. 25, Yogyakarta",
            "provinsi": "DI Yogyakarta",
            "kotaKabupaten": "Yogyakarta",
            "latitude": -7.7828,
            "longitude": 110.3675,
            "priceRange": "sedang",
            "rating": 4.7,
            "timeMinutes": 180,
            "contact": "+62 274 345678",
            "imageUrl": "",
            "imagePath": "",
            "isCultural": True,
            "umkmId": None
        },
        {
            "name": "Kafe Budaya Jogja",
            "category": "kafe",
            "description": "Kafe dengan konsep budaya Yogyakarta. Menu kuliner tradisional disajikan dengan suasana yang instagramable.",
            "address": "Jl. Prawirotaman No. 40, Yogyakarta",
            "provinsi": "DI Yogyakarta",
            "kotaKabupaten": "Yogyakarta",
            "latitude": -7.8139,
            "longitude": 110.3692,
            "priceRange": "sedang",
            "rating": 4.4,
            "timeMinutes": 60,
            "contact": "+62 274 456789",
            "imageUrl": "",
            "imagePath": "",
            "isCultural": True,
            "umkmId": None
        },
        {
            "name": "Galeri Seni Rupa Jogja",
            "category": "seni",
            "description": "Galeri seni rupa dengan karya seniman Yogyakarta. Lukisan, patung, dan kerajinan seni kontemporer.",
            "address": "Jl. Tirtodipuran No. 30, Yogyakarta",
            "provinsi": "DI Yogyakarta",
            "kotaKabupaten": "Yogyakarta",
            "latitude": -7.7819,
            "longitude": 110.3683,
            "priceRange": "mahal",
            "rating": 4.8,
            "timeMinutes": 90,
            "contact": "+62 274 567890",
            "imageUrl": "",
            "imagePath": "",
            "isCultural": True,
            "umkmId": None
        },

        # 26-30: Kerajinan Khas Daerah
        {
            "name": "Kerajinan Kulit Imogiri",
            "category": "kulit",
            "description": "Kerajinan kulit dari Imogiri. Tas, dompet, dan aksesoris kulit dengan kualitas premium.",
            "address": "Jl. Imogiri Barat No. 12, Yogyakarta",
            "provinsi": "DI Yogyakarta",
            "kotaKabupaten": "Yogyakarta",
            "latitude": -7.8833,
            "longitude": 110.3833,
            "priceRange": "mahal",
            "rating": 4.6,
            "timeMinutes": 100,
            "contact": "+62 274 678901",
            "imageUrl": "",
            "imagePath": "",
            "isCultural": True,
            "umkmId": None
        },
        {
            "name": "Anyaman Rotan Jogja",
            "category": "rotan",
            "description": "Kerajinan anyaman rotan untuk furniture dan dekorasi. Kursi, meja, dan keranjang dengan desain ergonomis.",
            "address": "Jl. Magelang KM 6, Yogyakarta",
            "provinsi": "DI Yogyakarta",
            "kotaKabupaten": "Yogyakarta",
            "latitude": -7.7333,
            "longitude": 110.3833,
            "priceRange": "sedang",
            "rating": 4.4,
            "timeMinutes": 120,
            "contact": "+62 274 789012",
            "imageUrl": "",
            "imagePath": "",
            "isCultural": True,
            "umkmId": None
        },
        {
            "name": "Souvenir Mandalika",
            "category": "souvenir",
            "description": "Souvenir khas Yogyakarta dengan berbagai pilihan. Gantungan kunci, magnet, dan miniatur candi.",
            "address": "Jl. Malioboro No. 65, Yogyakarta",
            "provinsi": "DI Yogyakarta",
            "kotaKabupaten": "Yogyakarta",
            "latitude": -7.795,
            "longitude": 110.3664,
            "priceRange": "murah",
            "rating": 4.2,
            "timeMinutes": 25,
            "contact": "+62 274 890123",
            "imageUrl": "",
            "imagePath": "",
            "isCultural": True,
            "umkmId": None
        },
        {
            "name": "Kerajinan Gerabah Kasongan",
            "category": "gerabah",
            "description": "Gerabah tangan dari Kasongan. Pot bunga, vas, dan dekorasi rumah dengan teknik pembakaran tradisional.",
            "address": "Jl. Kasongan No. 8, Yogyakarta",
            "provinsi": "DI Yogyakarta",
            "kotaKabupaten": "Bantul",
            "latitude": -7.8167,
            "longitude": 110.3167,
            "priceRange": "sedang",
            "rating": 4.5,
            "timeMinutes": 80,
            "contact": "+62 274 901234",
            "imageUrl": "",
            "imagePath": "",
            "isCultural": True,
            "umkmId": None
        },
        {
            "name": "Toko Jamu Tradisional",
            "category": "jamu",
            "description": "Jamu tradisional Yogyakarta dengan resep turun temurun. Berbagai jenis jamu untuk kesehatan dan kecantikan.",
            "address": "Jl. Tugu No. 15, Yogyakarta",
            "provinsi": "DI Yogyakarta",
            "kotaKabupaten": "Yogyakarta",
            "latitude": -7.7833,
            "longitude": 110.3667,
            "priceRange": "murah",
            "rating": 4.3,
            "timeMinutes": 30,
            "contact": "+62 274 012345",
            "imageUrl": "",
            "imagePath": "",
            "isCultural": True,
            "umkmId": None
        }
    ]

    return umkm_data

def save_umkm_to_json():
    """Save UMKM data to JSON file"""
    data = create_umkm_data()

    with open('umkm_yogyakarta.json', 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

    print(f"✅ Created {len(data)} UMKM entries and saved to umkm_yogyakarta.json")

    # Print summary
    categories = {}
    for item in data:
        cat = item['category']
        categories[cat] = categories.get(cat, 0) + 1

    print("\n📊 Category Distribution:")
    for cat, count in categories.items():
        print(f"  {cat}: {count} UMKM")

if __name__ == '__main__':
    save_umkm_to_json()
